---
- hosts: all
  become: true
  vars:
    mysql_root_password: root
    mysql_databases:
      - name: librebooking
    mysql_users:
      - name: lb_user
        password: password
        host: 127.0.0.1
  roles:
    - { role: geerlingguy.mysql }

