---
- hosts: all
  become: true
  vars:
    mysql_root_password: root
    mysql_databases:
      - name: librebooking
    mysql_users:
      - name: lb_user
        host: "localhost"
        password: password
        priv: "*.*:ALL"
  roles:
    - { role: geerlingguy.mysql }

