---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: install librebooking php modules
      apt:
        pkg:
          - php-ctype
          - php-curl
          - php-fileinfo
          - php-json
          - php-mbstring
          - php-mysqli
          - php-pdo
          - php-ldap
          - php-tokenizer
          - php-xml
          - php-gd
          - php-bcmath
          - composer
    - name: setup apache2 modules
      shell: |
        a2enmod headers
        a2enmod rewrite
    - name: clone code
      shell: |
        cd /var/www/html
        git clone https://github.com/LibreBooking/librebooking.git
        cd /var/www/html/librebooking
        mkdir -p ./tpl_c
        chmod 0777 ./tpl_c
        cd /var/www/html
        chown -R www-data:www-data librebooking
    - name: set www-data account for shell access
      user:
        name: www-data
        shell: /bin/bash
    - name: run composer install
      shell: |
        cd /var/www/html/librebooking
        composer -n install
    - name: setup config file
      shell: |
        cd /var/www/html/librebooking/config
        cp config.dist.php config.php
        chown www-data:www-data config.php
    - name: edit the install.password in config.php
      lineinfile:
        path: /var/www/html/librebooking/config/config.php
        regexp: "^(\\s*'install.password') => '',"
        line: "\\1 => 'password',"
        backrefs: true
    - name: edit the script.url in config.php
      lineinfile:
        path: /var/www/html/librebooking/config/config.php
        regexp: "^(\\s*'script.url') => '',"
        line: "\\1 => 'http://{{ ansible_fqdn }}/librebooking/Web',"
        backrefs: true

