# Run this playbook third
# This playbook installs the latest apache, php and fpm
# The versions are set by the distribution-release
# The script will move the index.html in the DOCROOT
# and replace it with index.php, you may browse
# to that url to validate proper php operation.
# and this playbook installs the apache php module
---
- hosts: all
  become: true
  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: '{{ ansible_fqdn }}'
        documentroot: /var/www/html
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/example"
  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm

  tasks:
    - name: create index.php
      shell: |
        mv /var/www/html/index.html /var/www/
        echo "<?php" >> /var/www/html/index.php
        echo "phpinfo();" >> /var/www/html/index.php
        echo "?>" >> /var/www/html/index.php

    - name: install libapache2-mod-php
      apt:
        name:
          - libapache2-mod-php
     
      
