---
- hosts: all
  tasks:
    - name: Add pam su for ansible user
      become: true
      ansible.builtin.blockinfile:
        path: /etc/pam.d/su
        insertafter: "auth       sufficient pam_rootok.so"
        block: |
          auth  [success=ignore default=1] pam_succeed_if.so user = ansible
          auth  sufficient pam_succeed_if.so use_uid user ingroup ansible

          
